version: "3.7"
services:
    web_service:
        build:
            args:
                user: web
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            -  8001:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
            - ./docker/db:/docker-entrypoint-initdb.d
        ports:
            - 3307:3306
        depends_on:
            - web_service
        networks:
            - microservices

networks:
    microservices:
        driver: bridge

volumes:
    mysql_data:
