version: "3.7"
services:
    web_service:
        build:
            args:
                user: web
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - mysql
        volumes:
            - ./:/var/www
        networks:
            - microservices

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    mysql:
        image: mysql:latest
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        networks:
            - microservices

networks:
    microservices:
        driver: bridge

volumes:
    mysql_data:
